#!/usr/bin/env python3

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Author: Manuel Bucher <dev@manuelbucher.com>
# Date: 2023-01-09

# https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html

import os
import sys
import json

def main():
    if len(sys.argv) > 1 and sys.argv[1] == "supports":
        return 0
    context, book = json.load(sys.stdin)

    files = os.listdir('archive')
    files.sort()
    files.reverse()
    new = []
    for file in files:
        if not file.startswith('meeting-'):
            continue
        if not file.endswith('.md'):
            continue
        name = file.split('.')[0]
        new.append( {"Chapter": {
                "name": file[:-3],
                "content": open(f'archive/{file}').read(),
                "number": None,
                "sub_items": [],
                "path": file,
                "source_path": file,
                "parent_names": []
        }})
    book["sections"] = new + book["sections"]

    print(json.dumps(book))

if __name__ == '__main__':
    sys.exit(main())
