#!/usr/bin/env python3

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Author: Manuel Bucher <dev@manuelbucher.com>
# Date: 2023-01-09

import os

def main():
    print('# Summary')
    files = os.listdir('archive')
    files.sort()
    files.reverse()
    for file in files:
        if not file.startswith('meeting-'):
            continue
        if not file.endswith('.md'):
            continue
        name = file.split('.')[0]
        print(f'[{name}](./{file})')

if __name__ == '__main__':
    main()
