#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Author: Manuel Bucher <dev@manuelbucher.com>
# Date: 2023-01-10

# Requirements:
#
#  * python
#  * curl
#  * pandoc
#
# Uses the latest download from the Download folder to extract the public
# meeting notes from. The format should be docx, because of
# https://stackoverflow.com/a/24896746, but odt works as well.

set -euxo pipefail

# Use last downloaded file for meeting notes. If there is a newer file use `touch` on the
# meeting notes to convert
DOWNLOAD_DIR="$HOME/Downloads"
INPUT_FILE="$DOWNLOAD_DIR/$(ls -Art $DOWNLOAD_DIR | tail -n 1)"

# Convert to markdown
pandoc --wrap=none -t commonmark_x -i "${INPUT_FILE}" -o "meeting-notes.0.md"

# extract part between "--- public ---" and "--- private ---"
./extract meeting-notes.0.md

# Regenerate index of meeting notes
./summary > archive/SUMMARY.md

# Add new files for next commit
git add archive/

# Show diff to commit for review
git diff --staged --color=always | less -R

# Write commit message, but ask for confirmation
git commit -m "Add meeting notes" -e

# show the commit for last review before pushing
git --no-pager show HEAD

# https://stackoverflow.com/a/1885542
read -p "upload changes? [y/N]?" CONT
if [ "$CONT" = "y" ]; then
  git push
fi
